services:
  db:
    image: mariadb:11.5.2
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: yoyakudb
      MARIADB_USER: user01
      MARIADB_PASSWORD: user01pass
      MARIADB_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  php:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
volumes:
  db-data:
